# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    schema: PDV
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Logger configuration
logging:
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080
flyway:
  enabled: true
  validate-on-migrate: true
